spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/do_connect
    username: root
    password: Apple12345678
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true